data_origin: extracted
references:
  - README.md
  - cm5/README.md
  - cm5/radxa-cm5-io-board/README.md
  - https://rock.sh/cm5
  - cm5/radxa-cm5-io-board/radxa_cm5_io_board_v2200_schematic.pdf
last_verified_date: 2026-03-05
