data_origin: extracted
references:
  - README.md
  - nx5/README.md
  - nx5/radxa-nx5-io-board/README.md
  - https://rock.sh/nx5
  - nx5/radxa-nx5-io-board/radxa_nx5_io_board_v1.4_schematic.pdf
last_verified_date: 2026-03-05
